### ISSUE TITLE
Support for horizontal transitions

### ISSUE THREAD

**Issue by zachgrayio** [hnvn/flutter_flip_panel#1]
I'm wondering how hard it would be to extend the library to create horizontal animations, similar to a book.

**Comment by zachgrayio** [comment]
Page curl would be very cool, but yeah, I've looked at the other implementations and they do indeed use OpenGL on android and it's a built-in transition type in iOS.

Simple card flip is probably better than nothing and actually in scope for this lib. If you can point me in the right direction I can probably add this functionality myself as well.

**Comment by zachgrayio** [comment]
There is an implementation out there using only android's `Canvas`, and it might be possible to draw some inspiration from this for page curls: https://github.com/moritz-wundke/android-page-curl/blob/master/src/com/mystictreegames/pagecurl/PageCurlView.java

**Comment by hnvn** [comment]
It seems possible to implement in Flutter, but it's still far from page curl look and feel. By the way, A guy has extended my project to give an implementation with gesture controller: https://github.com/jmolins/flutboard

**Comment by zachgrayio** [comment]
Ah, that's pretty cool
