### ISSUE TITLE
Please fix the padding issue in ReverseCountDown

### ISSUE THREAD

**Issue by kadarsh11** [hnvn/flutter_flip_panel#16]
Hi Hung,

Thanks for making this great package....Saved a lot of time for me.

Please fix the reverseCountdown function. Padding in this function is by deafult set to 180. 

Please change the padding at line no 282 

```dart  
padding: const EdgeInsets.only(top: 180.0)
```

**To**
```dart  
padding: const EdgeInsets.only(top: 3.0)
// Change 180 to anything you want.
```

**Comment by hnvn** [comment]
fixed
