### ISSUE TITLE
Pause/Resume functionality!

### ISSUE THREAD

**Issue by gokhanbaydar** [hnvn/flutter_flip_panel#7]
Hello,

I am very new to Flutter and found this great flip panel, first of all thanks for the hard work it seems to work excellent. However, I think an important functionality to start with a method, pause & resume seems to be missing, at least to me :)

**Comment by hnvn** [comment]
You can try to pause/resume a `Stream`. I don't know how to do it exactly but as far as I know, you can do it with `RxDart`.
